# Generated by Django 4.1.13 on 2024-03-25 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='country',
            field=models.CharField(max_length=3),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('commission', models.CharField(max_length=20)),
                ('tuition_fee', models.CharField(max_length=20)),
                ('application_fee', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=20)),
                ('intake', models.CharField(max_length=20)),
                ('sector', models.CharField(max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schools.school')),
            ],
        ),
    ]
