# Generated by Django 4.1.13 on 2024-03-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0004_alter_school_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='city',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='school',
            name='state',
            field=models.CharField(max_length=50),
        ),
    ]
