# Generated by Django 4.1.13 on 2024-03-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0005_alter_school_city_alter_school_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='commission',
            field=models.CharField(max_length=255),
        ),
    ]
