# Generated by Django 4.1.13 on 2024-03-26 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0006_alter_course_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='commission',
            field=models.CharField(max_length=1000),
        ),
    ]
