# Generated by Django 4.1.13 on 2024-03-31 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0007_alter_course_commission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
